### ISSUE TITLE
Make a release please.

### ISSUE THREAD

**Issue by Chris2011** [ceylon/ceylon-ide-netbeans#1]
It would be great, if you can craete a 0.0.1 pre-release or so that we can test it. I know we can compile it by our own but if the features are still usable, it would be good to hold it for a releasable version.

Regards

Chris

**Comment by bjansen** [comment]
I guess the code needs a serious dusting before we can release something, especially if we want to ship it with Ceylon 1.3.3 :)

**Comment by Chris2011** [comment]
Thx for the info. Is this plugin based on this article? I mean is this plugin mentioned in this article or is it independent from that: https://blogs.oracle.com/geertjan/ceylon-for-netbeans-ide-801

**Comment by bjansen** [comment]
The plugin mentioned in that article was originally written by Geertjan Wielenga, and is available [here](https://github.com/GeertjanWielenga/NetCeylonBeans). I wrote ceylon-ide-netbeans from scratch mostly in Ceylon, and borrowed a few things from Geertjan's original project while translating code from Java to Ceylon.

**Comment by Chris2011** [comment]
Ok fine, I think his repo is outdated.

**Comment by bjansen** [comment]
I've resurrected the plugin, fixed the build errors and added it to our continuous integration server. You can download nightly builds here:

https://ci-ceylon.rhcloud.com/job/ceylon-ide-netbeans/

I can't guarantee that it's in a stable state, because I haven't had much time to test it, but IIRC with this version you can either create Ceylon projects directly, or add Ceylon files to regular Java and NB module projects. 

What might work: autocompletion, error highlighting and quick fixes.

**Comment by Chris2011** [comment]
Nice, thx :)

**Comment by bjansen** [comment]
Closing, because I set up nightly builds. I'll do a real release once the plugin is stable enough to be published on the official plugins portal.
